# This DEMO file was @generated by uninix alpha-1
# IT is not intended to be used in production or manually edited.
# This is a basic demo file intended to be a placeholder until
# the official uni.adapt.nix file is able to be configured.

args@{
  release ? true,
  uninixLib,
  target ? null,
  lib,
  workspaceSource,
  gradle,
  compileMode ? null,
  gradlePackages,
  workspaceGen,
}:
let
  workspaceSource = if args.workspaceSource == null then ./. else args.workspaceSource;
in let
  inherit (uninixLib) genDrvsByVersion decideVersion;
  inherit (gradle) makeGradlePkg fetchGradle;
  versionsBySettings = {};
  overridableMakeGradlePkg = f:
    let
      drvs = genDrvsByVersion versionsBySettings ({ version, versionName }: makeGradlePkg ({ inherit release version target; } // (f versionName)));
    in { compileMode ? null, versionName ? decideVersion compileMode release }:
      let drv = drvs.${versionName}; in if compileMode == null then drv else drv.override { inherit compileMode; };
in
{
  uninixVersion = "alpha-1";
  workspace = workspaceGen;
  "unknown".workspace.version = overridableMakeGradlePkg (versionName: {
    name = workspaceGen.minecraft.sort.name;
    version = workspaceGen.minecraft.sort.version;
    src = fetchGradle workspaceSource;
  });
}