name: Bug Report
labels: "bug"
body:
- type: markdown
  attributes:
    value: Before raising an issue, please search for existing issues to avoid creating duplicates. For questions and support please use [Discord](https://polyfrost.cc/discord).
- type: textarea
  id: bug-description
  attributes:
    label: Bug description
    value: Summarize the bug encountered concisely
  validations:
    required: true
- type: textarea
  id: version-data
  description: The version data e.g Minecraft 2.10.2, OneConfig v0.1-alpha, Windows 12, etc.
- type: textarea
  id: steps-to-reproduce
  attributes:
    label: Steps to reproduce
    value: Describe the steps to reproduce the issue
  validations:
    required: true
- type: textarea
  id: expected-behavior
  attributes:
    label: Expected behavior
    value: Describe what you should see instead
- type: textarea
  id: example-repository
  attributes:
    label: Example repository
    value: If possible, please create an [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug and link it here in the bug report
- type: textarea
  id: anything-else
  attributes:
    label: Anything else?
    value: Let us know if you have any additional feedback!
