//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::AssetKind;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "asset")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	#[sea_orm(column_type = "Text", nullable, unique)]
	pub storage_path: Option<String>,
	#[sea_orm(column_type = "Text", nullable)]
	pub url: Option<String>,
	pub asset_kind: AssetKind,
	#[sea_orm(column_type = "Text", nullable)]
	pub content_type: Option<String>,
	#[sea_orm(column_type = "Text", nullable)]
	pub hash: Option<String>,
	pub created_at: DateTimeWithTimeZone,
	pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::bundles::Entity")]
	Bundles,
	#[sea_orm(has_many = "super::collections::Entity")]
	Collections,
	#[sea_orm(has_many = "super::cosmetic::Entity")]
	Cosmetic,
}

impl Related<super::bundles::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Bundles.def()
	}
}

impl Related<super::collections::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Collections.def()
	}
}

impl Related<super::cosmetic::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Cosmetic.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
