//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bundles_cosmetics")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub bundle_id: i32,
	#[sea_orm(primary_key, auto_increment = false)]
	pub cosmetic_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::bundles::Entity",
		from = "Column::BundleId",
		to = "super::bundles::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Bundles,
	#[sea_orm(
		belongs_to = "super::cosmetic::Entity",
		from = "Column::CosmeticId",
		to = "super::cosmetic::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Cosmetic,
}

impl Related<super::bundles::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Bundles.def()
	}
}

impl Related<super::cosmetic::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Cosmetic.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
