//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "bundles")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	#[sea_orm(column_type = "Text")]
	pub name: String,
	#[sea_orm(column_type = "Text", nullable)]
	pub description: Option<String>,
	pub asset_id: Option<i32>,
	pub enabled: bool,
	pub collection: Option<i32>,
	#[sea_orm(column_type = "Text", nullable)]
	pub stripe_product_id: Option<String>,
	#[sea_orm(column_type = "Text", nullable)]
	pub stripe_price_id: Option<String>,
	#[sea_orm(column_type = "Float", nullable)]
	pub base_price: Option<f32>,
	pub discount_rate: Option<i32>,
	pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::asset::Entity",
		from = "Column::AssetId",
		to = "super::asset::Column::Id",
		on_update = "NoAction",
		on_delete = "SetNull"
	)]
	Asset,
	#[sea_orm(has_many = "super::bundles_cosmetics::Entity")]
	BundlesCosmetics,
	#[sea_orm(
		belongs_to = "super::collections::Entity",
		from = "Column::Collection",
		to = "super::collections::Column::Id",
		on_update = "NoAction",
		on_delete = "SetNull"
	)]
	Collections,
}

impl Related<super::asset::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Asset.def()
	}
}

impl Related<super::bundles_cosmetics::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::BundlesCosmetics.def()
	}
}

impl Related<super::collections::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Collections.def()
	}
}

impl Related<super::cosmetic::Entity> for Entity {
	fn to() -> RelationDef {
		super::bundles_cosmetics::Relation::Cosmetic.def()
	}
	fn via() -> Option<RelationDef> {
		Some(super::bundles_cosmetics::Relation::Bundles.def().rev())
	}
}

impl ActiveModelBehavior for ActiveModel {}
