//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "collections")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	#[sea_orm(column_type = "Text")]
	pub name: String,
	#[sea_orm(column_type = "Text", nullable)]
	pub description: Option<String>,
	pub created_at: DateTimeWithTimeZone,
	pub asset_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::asset::Entity",
		from = "Column::AssetId",
		to = "super::asset::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Asset,
	#[sea_orm(has_many = "super::bundles::Entity")]
	Bundles,
	#[sea_orm(has_many = "super::cosmetic::Entity")]
	Cosmetic,
}

impl Related<super::asset::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Asset.def()
	}
}

impl Related<super::bundles::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Bundles.def()
	}
}

impl Related<super::cosmetic::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Cosmetic.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
