//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::CosmeticType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cosmetic_group")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	pub r#type: CosmeticType,
	#[sea_orm(column_type = "Text")]
	pub name: String,
	pub enabled: bool,
	pub created_at: DateTimeWithTimeZone,
	pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::cosmetic::Entity")]
	Cosmetic,
	#[sea_orm(has_many = "super::cosmetic_group_allowed_slot::Entity")]
	CosmeticGroupAllowedSlot,
}

impl Related<super::cosmetic::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Cosmetic.def()
	}
}

impl Related<super::cosmetic_group_allowed_slot::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::CosmeticGroupAllowedSlot.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
