//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::BodySlot;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cosmetic_group_allowed_slot")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub group_id: i32,
	#[sea_orm(primary_key, auto_increment = false)]
	pub slot: BodySlot,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::cosmetic_group::Entity",
		from = "Column::GroupId",
		to = "super::cosmetic_group::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	CosmeticGroup,
}

impl Related<super::cosmetic_group::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::CosmeticGroup.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
