//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::CosmeticType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "cosmetic")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	pub r#type: CosmeticType,
	pub asset_id: Option<i32>,
	#[sea_orm(column_type = "Text", nullable)]
	pub name: Option<String>,
	pub enabled: bool,
	pub created_at: DateTimeWithTimeZone,
	pub updated_at: DateTimeWithTimeZone,
	pub group_id: Option<i32>,
	#[sea_orm(column_type = "Text", nullable)]
	pub variant_name: Option<String>,
	#[sea_orm(column_type = "Text", nullable)]
	pub model_variant: Option<String>,
	pub variant_order: i32,
	#[sea_orm(column_type = "Text", nullable)]
	pub stripe_price_id: Option<String>,
	#[sea_orm(column_type = "Text", nullable)]
	pub stripe_product_id: Option<String>,
	#[sea_orm(column_type = "Float", nullable)]
	pub base_price: Option<f32>,
	pub discount_rate: Option<i32>,
	pub collection: Option<i32>,
	#[sea_orm(column_type = "Text", nullable)]
	pub description: Option<String>,
	pub purchase_count: i32,
	pub cover_asset_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::asset::Entity",
		from = "Column::AssetId",
		to = "super::asset::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Asset,
	#[sea_orm(has_many = "super::bundles_cosmetics::Entity")]
	BundlesCosmetics,
	#[sea_orm(
		belongs_to = "super::collections::Entity",
		from = "Column::Collection",
		to = "super::collections::Column::Id",
		on_update = "Cascade",
		on_delete = "SetNull"
	)]
	Collections,
	#[sea_orm(has_many = "super::cosmetic_allowed_slot::Entity")]
	CosmeticAllowedSlot,
	#[sea_orm(
		belongs_to = "super::cosmetic_group::Entity",
		from = "Column::GroupId",
		to = "super::cosmetic_group::Column::Id",
		on_update = "NoAction",
		on_delete = "SetNull"
	)]
	CosmeticGroup,
	#[sea_orm(has_many = "super::cosmetic_package::Entity")]
	CosmeticPackage,
	#[sea_orm(has_many = "super::player_equipped_cosmetic::Entity")]
	PlayerEquippedCosmetic,
	#[sea_orm(has_many = "super::player_owned_cosmetic::Entity")]
	PlayerOwnedCosmetic,
	#[sea_orm(has_many = "super::tags_cosmetic::Entity")]
	TagsCosmetic,
}

impl Related<super::asset::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Asset.def()
	}
}

impl Related<super::bundles_cosmetics::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::BundlesCosmetics.def()
	}
}

impl Related<super::collections::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Collections.def()
	}
}

impl Related<super::cosmetic_allowed_slot::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::CosmeticAllowedSlot.def()
	}
}

impl Related<super::cosmetic_group::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::CosmeticGroup.def()
	}
}

impl Related<super::cosmetic_package::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::CosmeticPackage.def()
	}
}

impl Related<super::player_equipped_cosmetic::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::PlayerEquippedCosmetic.def()
	}
}

impl Related<super::player_owned_cosmetic::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::PlayerOwnedCosmetic.def()
	}
}

impl Related<super::tags_cosmetic::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::TagsCosmetic.def()
	}
}

impl Related<super::bundles::Entity> for Entity {
	fn to() -> RelationDef {
		super::bundles_cosmetics::Relation::Bundles.def()
	}
	fn via() -> Option<RelationDef> {
		Some(super::bundles_cosmetics::Relation::Cosmetic.def().rev())
	}
}

impl Related<super::tags::Entity> for Entity {
	fn to() -> RelationDef {
		super::tags_cosmetic::Relation::Tags.def()
	}
	fn via() -> Option<RelationDef> {
		Some(super::tags_cosmetic::Relation::Cosmetic.def().rev())
	}
}

impl Related<super::user::Entity> for Entity {
	fn to() -> RelationDef {
		super::player_equipped_cosmetic::Relation::User.def()
	}
	fn via() -> Option<RelationDef> {
		Some(
			super::player_equipped_cosmetic::Relation::Cosmetic
				.def()
				.rev(),
		)
	}
}

impl ActiveModelBehavior for ActiveModel {}
