//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::TagType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tags")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	#[sea_orm(column_type = "Text", unique)]
	pub name: String,
	#[sea_orm(column_type = "Text", nullable)]
	pub description: Option<String>,
	pub tag_type: TagType,
	pub created_at: DateTimeWithTimeZone,
	#[sea_orm(column_type = "Text", nullable)]
	pub display_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::tags_cosmetic::Entity")]
	TagsCosmetic,
}

impl Related<super::tags_cosmetic::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::TagsCosmetic.def()
	}
}

impl Related<super::cosmetic::Entity> for Entity {
	fn to() -> RelationDef {
		super::tags_cosmetic::Relation::Cosmetic.def()
	}
	fn via() -> Option<RelationDef> {
		Some(super::tags_cosmetic::Relation::Tags.def().rev())
	}
}

impl ActiveModelBehavior for ActiveModel {}
