//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tracked_link_hits")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
	pub slug: String,
	#[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
	pub visitor_hash: String,
	pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::tracked_links::Entity",
		from = "Column::Slug",
		to = "super::tracked_links::Column::Slug",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	TrackedLinks,
}

impl Related<super::tracked_links::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::TrackedLinks.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
