//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::TransactionProvider;
use super::sea_orm_active_enums::TransactionStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "transaction")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	pub player_id: i32,
	pub provider: TransactionProvider,
	#[sea_orm(column_type = "Text", nullable)]
	pub stripe_payment_id: Option<String>,
	pub status: TransactionStatus,
	pub created_at: DateTimeWithTimeZone,
	#[sea_orm(column_type = "JsonBinary")]
	pub raw_metadata: Json,
	#[sea_orm(column_type = "Float", nullable)]
	pub amount: Option<f32>,
	pub discount_rate: Option<i32>,
	pub buyer: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::player_owned_cosmetic::Entity")]
	PlayerOwnedCosmetic,
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::Buyer",
		to = "super::user::Column::Id",
		on_update = "Cascade",
		on_delete = "SetNull"
	)]
	User2,
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::PlayerId",
		to = "super::user::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	User1,
}

impl Related<super::player_owned_cosmetic::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::PlayerOwnedCosmetic.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
