[versions]
command-api-v2 = "2.3.7+328a75ba68"

modmenu = "16.0.0-rc.1"
yacl = "3.8.0+1.21.9-fabric"
moulconfig = "3.11.0"

vulkanmod = "jkDMvvWU"

[libraries]
command-api-v2 = { module = "net.fabricmc.fabric-api:fabric-command-api-v2", version.ref = "command-api-v2" }

modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu"}
yacl = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl" }
moulconfig = { module = "org.notenoughupdates.moulconfig:common", version.ref = "moulconfig" }

vulkanmod = { module = "maven.modrinth:vulkanmod", version.ref = "vulkanmod" }

[bundles]
compat = ["modmenu", "yacl"]
