[versions]
command-api-v2 = "3.0.5+e2bdee78c3"

modmenu = "18.0.0-beta.1"
yacl = "3.9.0+26.1-fabric"
moulconfig = "3.11.0"
odin = "0.2.2"
skyblocker = "7OtCaJGB"
stella = "d12aec9c69"

vulkanmod = "0.6.8+26.1.2"

skycubed = "zCt0GMWK"
meowdding-lib = "4.2.5"
skyblock-api = "4.2.8"

[libraries]
command-api-v2 = { module = "net.fabricmc.fabric-api:fabric-command-api-v2", version.ref = "command-api-v2" }

modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu"}
yacl = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl" }
odin = { module = "maven.modrinth:odin", version.ref = "odin" }
skyblocker = { module = "maven.modrinth:skyblocker-liap", version.ref = "skyblocker" }
#stella = { module = "maven.modrinth:stella", version.ref = "stella"} I prefer modrinth but needed this to work befor I release
stella = { module = "com.github.Eclipse-5214.stella:stella-26.1", version.ref = "stella" }

moulconfig = { module = "org.notenoughupdates.moulconfig:common", version.ref = "moulconfig" }

vulkanmod = { module = "maven.modrinth:vulkanmod", version.ref = "vulkanmod" }

skycubed = { module = "maven.modrinth:skycubed", version.ref = "skycubed" }
meowdding-lib = { module = "me.owdding.meowdding-lib:meowdding-lib", version.ref = "meowdding-lib" }
skyblock-api = { module = "tech.thatgravyboat:skyblock-api", version.ref = "skyblock-api" }

[bundles]
compat = ["modmenu", "yacl", "odin", "skyblocker", "stella"]
