name: Build with nix

on: [push, pull_request, workflow_dispatch]
permissions:
    actions: write
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install Nix
              uses: nixbuild/nix-quick-install-action@v31
              with:
                  nix_conf: |
                      keep-env-derivations = true
                      keep-outputs = true

            - name: Cache nix store
              uses: nix-community/cache-nix-action@v6
              with:
                  primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
                  restore-prefixes-first-match: nix-${{ runner.os }}-
                  gc-max-store-size-linux: 1G
                  purge: true
                  purge-prefixes: nix-${{ runner.os }}-
                  purge-created: 0
                  purge-last-accessed: 0
                  purge-primary-key: never

            - uses: cachix/cachix-action@v15
              with:
                  name: polyfrost
                  authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
                  signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
                  skipPush: true

            - name: Check nix flake
              run: nix -L flake check --keep-going

            - name: Build backend with nix
              run: nix -L build .#backend

            - name: Push to Cachix
              run: cachix push polyfrost ./result

            - name: Upload built nix package
              uses: actions/upload-artifact@v4
              with:
                  name: backend
                  path: ./result/**/*
