[package]
name = "maven"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
chrono = "0.4.41"
quick-xml = { version = "0.38.0", features = ["serde", "serialize"] }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = "3.14.0"
