[versions]
minecraft = "1.21.1"
parchment = "2024.11.17"

rconfig = "3.0.11"

[libraries]
parchment = { module = "org.parchmentmc.data:parchment-1.21.1", version.ref = "parchment" }

rconfig = { module = "com.teamresourceful.resourcefulconfig:resourcefulconfig-common-1.21", version.ref = "rconfig"}

[bundles]
common-compat = ["rconfig"]