{
  "formatVersion": "1.1",
  "component": {
    "group": "org.polyfrost.oneconfig",
    "module": "1.8.9-forge",
    "version": "1.0.0-alpha.118",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-jvm",
          "version": {
            "requires": "0.27.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.electronwill.night-config",
          "module": "json",
          "version": {
            "requires": "3.6.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.electronwill.night-config",
          "module": "yaml",
          "version": {
            "requires": "3.6.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.31"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.polyfrost",
          "module": "isolated-lwjgl3-loader",
          "version": {
            "requires": "0.2.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.deftu",
          "module": "textile",
          "version": {
            "requires": "0.20.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.polyfrost",
          "module": "polyio",
          "version": {
            "requires": "0.1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.deftu",
          "module": "copycat",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.deftu",
          "module": "copycat-natives-windows-x64",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.deftu",
          "module": "copycat-natives-windows-x86",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.deftu",
          "module": "copycat-natives-linux-x64",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.deftu",
          "module": "copycat-natives-linux-x86",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.deftu",
          "module": "copycat-natives-linux-arm",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.deftu",
          "module": "copycat-natives-linux-arm64",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.deftu",
          "module": "copycat-natives-osx-x64",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.deftu",
          "module": "copycat-natives-osx-arm64",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.deftu",
          "module": "copycat-image-awt",
          "version": {
            "requires": "0.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.polyfrost",
          "module": "polyui",
          "version": {
            "requires": "1.11.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.hypixel",
          "module": "mod-api",
          "version": {
            "requires": "1.0.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.hypixel",
          "module": "hypixel-data",
          "version": {
            "requires": "0.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.polyfrost",
          "module": "polymixin",
          "version": {
            "requires": "0.8.4+build.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.0.18"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-common",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.deftu",
          "module": "enhancedeventbus",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-nanovg",
          "version": {
            "requires": "3.3.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.deftu",
          "module": "textile-1.8.9-forge",
          "version": {
            "requires": "0.20.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "attributes": {
            "org.polyfrost.oneconfig.loader.include": true
          }
        },
        {
          "group": "dev.deftu",
          "module": "omnicore-1.8.9-forge",
          "version": {
            "requires": "0.37.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "attributes": {
            "org.polyfrost.oneconfig.loader.include": true
          }
        }
      ],
      "files": [
        {
          "name": "1.8.9-forge-1.0.0-alpha.118.jar",
          "url": "1.8.9-forge-1.0.0-alpha.118.jar",
          "size": 201542,
          "sha512": "5d05854dc5b25aa902d611edba26eedfddbc957755e4291e90c0a46af7315d299361f8a054ebd0e83528c7fb06e313cb2ba6a2fb70f2c4758b8f67c5bca012e5",
          "sha256": "fe073fdfbf4bca14276f755b5bcaf9274f41b629f4e256597a630f0a73f19c36",
          "sha1": "60acf184bc2398bea0f3106acefa00a4ca31f7a6",
          "md5": "744b69a14342233a8ead4f7f97fcb855"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-jvm",
          "version": {
            "requires": "0.27.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.electronwill.night-config",
          "module": "json",
          "version": {
            "requires": "3.6.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.electronwill.night-config",
          "module": "yaml",
          "version": {
            "requires": "3.6.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.31"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.polyfrost",
          "module": "isolated-lwjgl3-loader",
          "version": {
            "requires": "0.2.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.deftu",
          "module": "textile",
          "version": {
            "requires": "0.20.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.polyfrost",
          "module": "polyio",
          "version": {
            "requires": "0.1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.deftu",
          "module": "copycat",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.deftu",
          "module": "copycat-natives-windows-x64",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.deftu",
          "module": "copycat-natives-windows-x86",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.deftu",
          "module": "copycat-natives-linux-x64",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.deftu",
          "module": "copycat-natives-linux-x86",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.deftu",
          "module": "copycat-natives-linux-arm",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.deftu",
          "module": "copycat-natives-linux-arm64",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.deftu",
          "module": "copycat-natives-osx-x64",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.deftu",
          "module": "copycat-natives-osx-arm64",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.deftu",
          "module": "copycat-image-awt",
          "version": {
            "requires": "0.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.polyfrost",
          "module": "polyui",
          "version": {
            "requires": "1.11.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.hypixel",
          "module": "mod-api",
          "version": {
            "requires": "1.0.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.hypixel",
          "module": "hypixel-data",
          "version": {
            "requires": "0.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.polyfrost",
          "module": "polymixin",
          "version": {
            "requires": "0.8.4+build.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.0.18"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-common",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.deftu",
          "module": "enhancedeventbus",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "dev.deftu",
          "module": "textile-1.8.9-forge",
          "version": {
            "requires": "0.20.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "attributes": {
            "org.polyfrost.oneconfig.loader.include": true
          }
        },
        {
          "group": "dev.deftu",
          "module": "omnicore-1.8.9-forge",
          "version": {
            "requires": "0.37.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "attributes": {
            "org.polyfrost.oneconfig.loader.include": true
          }
        },
        {
          "group": "me.djtheredstoner",
          "module": "DevAuth-forge-legacy",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "1.8.9-forge-1.0.0-alpha.118.jar",
          "url": "1.8.9-forge-1.0.0-alpha.118.jar",
          "size": 201542,
          "sha512": "5d05854dc5b25aa902d611edba26eedfddbc957755e4291e90c0a46af7315d299361f8a054ebd0e83528c7fb06e313cb2ba6a2fb70f2c4758b8f67c5bca012e5",
          "sha256": "fe073fdfbf4bca14276f755b5bcaf9274f41b629f4e256597a630f0a73f19c36",
          "sha1": "60acf184bc2398bea0f3106acefa00a4ca31f7a6",
          "md5": "744b69a14342233a8ead4f7f97fcb855"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "1.8.9-forge-1.0.0-alpha.118-sources.jar",
          "url": "1.8.9-forge-1.0.0-alpha.118-sources.jar",
          "size": 192145,
          "sha512": "96db4110f9ecf6412bda392148a48193d81e74335e4c2b29468151c86718f768c0d629993af44b748d533310e316a86a562346dc03177053847826a02656fe3b",
          "sha256": "c43387f7b204738f4f72980c593d192b9eddd225b3780854055e5b996ab2090c",
          "sha1": "b6e5e3442a3c228c102dbbd4bfbfb80fc97f7d91",
          "md5": "6d055ddcd7cefe2c7389adba9dfb10b0"
        }
      ]
    },
    {
      "name": "oneConfigModulesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "dev.deftu",
          "module": "textile-1.8.9-forge",
          "version": {
            "requires": "0.20.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "attributes": {
            "org.polyfrost.oneconfig.loader.include": true
          }
        },
        {
          "group": "dev.deftu",
          "module": "omnicore-1.8.9-forge",
          "version": {
            "requires": "0.37.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "attributes": {
            "org.polyfrost.oneconfig.loader.include": true
          }
        },
        {
          "group": "org.polyfrost.oneconfig",
          "module": "commands",
          "version": {
            "requires": "1.0.0-alpha.118"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "attributes": {
            "org.polyfrost.oneconfig.loader.include": true
          }
        },
        {
          "group": "org.polyfrost.oneconfig",
          "module": "config",
          "version": {
            "requires": "1.0.0-alpha.118"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "attributes": {
            "org.polyfrost.oneconfig.loader.include": true
          }
        },
        {
          "group": "org.polyfrost.oneconfig",
          "module": "config-impl",
          "version": {
            "requires": "1.0.0-alpha.118"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "attributes": {
            "org.polyfrost.oneconfig.loader.include": true
          }
        },
        {
          "group": "org.polyfrost.oneconfig",
          "module": "events",
          "version": {
            "requires": "1.0.0-alpha.118"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "attributes": {
            "org.polyfrost.oneconfig.loader.include": true
          }
        },
        {
          "group": "org.polyfrost.oneconfig",
          "module": "hud",
          "version": {
            "requires": "1.0.0-alpha.118"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "attributes": {
            "org.polyfrost.oneconfig.loader.include": true
          }
        },
        {
          "group": "org.polyfrost.oneconfig",
          "module": "internal",
          "version": {
            "requires": "1.0.0-alpha.118"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "attributes": {
            "org.polyfrost.oneconfig.loader.include": true
          }
        },
        {
          "group": "org.polyfrost.oneconfig",
          "module": "ui",
          "version": {
            "requires": "1.0.0-alpha.118"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "attributes": {
            "org.polyfrost.oneconfig.loader.include": true
          }
        },
        {
          "group": "org.polyfrost.oneconfig",
          "module": "utils",
          "version": {
            "requires": "1.0.0-alpha.118"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "attributes": {
            "org.polyfrost.oneconfig.loader.include": true
          }
        },
        {
          "group": "org.polyfrost.oneconfig.dependencies",
          "module": "legacy",
          "version": {
            "requires": "1.0.0-alpha.118"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "attributes": {
            "org.polyfrost.oneconfig.loader.include": true,
            "org.polyfrost.oneconfig.loader.jij": true
          }
        }
      ],
      "files": [
        {
          "name": "1.8.9-forge-1.0.0-alpha.118-one-config-modules.jar",
          "url": "1.8.9-forge-1.0.0-alpha.118-one-config-modules.jar",
          "size": 378,
          "sha512": "0603b9d51ced2471b0ddbc6e04a2f71436f499d9c453a4d2afc67b3b69fa123db5d048d47e28c1fa717674e8d7bc32f7e744f250e8872f2e67de3d7636ce58d6",
          "sha256": "3687af858995921c8141d46379aaef42c161637cfc13b94a7398600c425f8a0c",
          "sha1": "a380f4ffbd0bbbf13454f8e2ecfacc53f762e648",
          "md5": "c883b98dfdced28780a3c9549a393ddb"
        }
      ],
      "capabilities": [
        {
          "group": "org.polyfrost.oneconfig",
          "name": "1.8.9-forge-one-config-modules",
          "version": "1.0.0-alpha.118+1.8.9-forge"
        }
      ]
    },
    {
      "name": "oneConfigModulesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "1.8.9-forge-1.0.0-alpha.118-one-config-modules.jar",
          "url": "1.8.9-forge-1.0.0-alpha.118-one-config-modules.jar",
          "size": 378,
          "sha512": "0603b9d51ced2471b0ddbc6e04a2f71436f499d9c453a4d2afc67b3b69fa123db5d048d47e28c1fa717674e8d7bc32f7e744f250e8872f2e67de3d7636ce58d6",
          "sha256": "3687af858995921c8141d46379aaef42c161637cfc13b94a7398600c425f8a0c",
          "sha1": "a380f4ffbd0bbbf13454f8e2ecfacc53f762e648",
          "md5": "c883b98dfdced28780a3c9549a393ddb"
        }
      ],
      "capabilities": [
        {
          "group": "org.polyfrost.oneconfig",
          "name": "1.8.9-forge-one-config-modules",
          "version": "1.0.0-alpha.118+1.8.9-forge"
        }
      ]
    }
  ]
}
